version: '3.8'
services:
  vuejs:
    container_name: compro-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./logs:/var/log/nginx
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  node_modules: